# Generated by Django 3.2.20 on 2024-01-03 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20231224_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='description_of_research',
            field=models.TextField(blank=True, help_text="This section, including references, cannot exceed 20.000 char and is expected to detail how the specific scientific/computational goals will be achieved and to define detailed workplan.\nProposals will be evaluated on both scientific and technical merit. The provided information should be sufficient for the reviewers in your research field to provide a scientific evaluation of the proposal and to understand if the computational methodology is suitable to reach the project's goals. Furthermore, a general scientific cross-comparison with proposals in other disciplines should be feasible.\nThe list of the topics that MUST be detailed/included follows (please notice that incomplete descriptions will lead to the project rejection).\n- Scientific framework\n- Project objectives\n- Theoretical and computational methods employed\n- List of the applications to be used and their performance on parallel architectures (scalability and load-balancing)\n- Detailed workplan and timetable of the activities (GANTT)\n- Place the proposed research in the context of competing work in your discipline\n- Explain what scientific advances you expect to be enabled by an award that justifies an allocation of large-scale resources", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description of Research'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_of_research',
            field=models.TextField(blank=True, help_text="This section, including references, cannot exceed 20.000 char and is expected to detail how the specific scientific/computational goals will be achieved and to define detailed workplan.\nProposals will be evaluated on both scientific and technical merit. The provided information should be sufficient for the reviewers in your research field to provide a scientific evaluation of the proposal and to understand if the computational methodology is suitable to reach the project's goals. Furthermore, a general scientific cross-comparison with proposals in other disciplines should be feasible.\nThe list of the topics that MUST be detailed/included follows (please notice that incomplete descriptions will lead to the project rejection).\n- Scientific framework\n- Project objectives\n- Theoretical and computational methods employed\n- List of the applications to be used and their performance on parallel architectures (scalability and load-balancing)\n- Detailed workplan and timetable of the activities (GANTT)\n- Place the proposed research in the context of competing work in your discipline\n- Explain what scientific advances you expect to be enabled by an award that justifies an allocation of large-scale resources", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description of Research'),
        ),
    ]
