# Generated by Django 3.2.20 on 2024-01-03 13:31

import django.core.validators
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20240103_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('B', 'Large research project, connected to a national or international competitive project (up to 100.000 standard hours)'), ('BI', 'Industrial research project (i.e. "conto terzi") (up to 100.000 standard hours)'), ('C', 'Medium research project, connected to a national competitive project (up to 50.000 standard hours)'), ('D', 'PhD student support project (up to 20.000 standard hours per year)'), ('E', 'MSc thesis project (up to 10.000 standard hours)'), ('F', 'Support to teaching, including group projects (up to 25.000 standard hours)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('B', 'Large research project, connected to a national or international competitive project (up to 100.000 standard hours)'), ('BI', 'Industrial research project (i.e. "conto terzi") (up to 100.000 standard hours)'), ('C', 'Medium research project, connected to a national competitive project (up to 50.000 standard hours)'), ('D', 'PhD student support project (up to 20.000 standard hours per year)'), ('E', 'MSc thesis project (up to 10.000 standard hours)'), ('F', 'Support to teaching, including group projects (up to 25.000 standard hours)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.CharField(default='\nWe do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!\n        ', max_length=10000, validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description_of_research',
            field=martor.models.MartorField(blank=True, help_text="This section, including references, cannot exceed 20.000 char and is expected to detail how the specific scientific/computational goals will be achieved and to define detailed workplan.<br />\nProposals will be evaluated on both scientific and technical merit. The provided information should be sufficient for the reviewers in your research field to provide a scientific evaluation of the proposal and to understand if the computational methodology is suitable to reach the project's goals. Furthermore, a general scientific cross-comparison with proposals in other disciplines should be feasible.<br />\nThe list of the topics that MUST be detailed/included follows (please notice that incomplete descriptions will lead to the project rejection).<br />\n- Scientific framework<br />\n- Project objectives<br />\n- Theoretical and computational methods employed<br />\n- List of the applications to be used and their performance on parallel architectures (scalability and load-balancing)<br />\n- Detailed workplan and timetable of the activities (GANTT)<br />\n- Place the proposed research in the context of competing work in your discipline<br />\n- Explain what scientific advances you expect to be enabled by an award that justifies an allocation of large-scale resources", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description of Research'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='\nWe do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!\n        ', max_length=10000, validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_of_research',
            field=martor.models.MartorField(blank=True, help_text="This section, including references, cannot exceed 20.000 char and is expected to detail how the specific scientific/computational goals will be achieved and to define detailed workplan.<br />\nProposals will be evaluated on both scientific and technical merit. The provided information should be sufficient for the reviewers in your research field to provide a scientific evaluation of the proposal and to understand if the computational methodology is suitable to reach the project's goals. Furthermore, a general scientific cross-comparison with proposals in other disciplines should be feasible.<br />\nThe list of the topics that MUST be detailed/included follows (please notice that incomplete descriptions will lead to the project rejection).<br />\n- Scientific framework<br />\n- Project objectives<br />\n- Theoretical and computational methods employed<br />\n- List of the applications to be used and their performance on parallel architectures (scalability and load-balancing)<br />\n- Detailed workplan and timetable of the activities (GANTT)<br />\n- Place the proposed research in the context of competing work in your discipline<br />\n- Explain what scientific advances you expect to be enabled by an award that justifies an allocation of large-scale resources", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description of Research'),
        ),
    ]
