# Generated by Django 3.2.20 on 2024-01-03 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20240103_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.CharField(help_text='One-line description of the project.', max_length=10000, validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='One-line description of the project.', max_length=10000, validators=[django.core.validators.MinLengthValidator(10, 'The project description must be > 10 characters.')]),
        ),
    ]
