# Generated by Django 3.2.20 on 2024-01-03 13:56

import django.core.validators
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20240103_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='financed_project_text',
            field=models.TextField(blank=True, help_text='If this project is financed by a grant, please upload the grant text here.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='financed_project_text',
            field=models.FileField(blank=True, help_text='If this project is financed by a grant, please upload the grant text here.', null=True, upload_to='financed_project_text'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='computational_approach',
            field=martor.models.MartorField(blank=True, help_text="Provide quantitative evidence of the HPC performances of the production application you will adopt in the project (scalability, efficiency, \nI/O performances). Parallel performances in either strong or weak scaling mode should be provided. Weak scaling behaviors are probed by holding \nper-processor computational work constant (e.g., the size of the mesh on a processor is held constant) as the total problem size grows with number \nof processors. Strong scaling behaviors are probed by holding the total problem size constant as the processor count grows, thereby decreasing \nthe per-processor computational work. Benchmark data should be provided in either tabular or graphical form, or both; the speedup curve should \nbe supplied as well for strong scaling examples. Where appropriate, characterize the application's single-node performance (ex. percent of peak).", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Computational Approach'),
        ),
        migrations.AlterField(
            model_name='project',
            name='computational_approach',
            field=martor.models.MartorField(blank=True, help_text="Provide quantitative evidence of the HPC performances of the production application you will adopt in the project (scalability, efficiency, \nI/O performances). Parallel performances in either strong or weak scaling mode should be provided. Weak scaling behaviors are probed by holding \nper-processor computational work constant (e.g., the size of the mesh on a processor is held constant) as the total problem size grows with number \nof processors. Strong scaling behaviors are probed by holding the total problem size constant as the processor count grows, thereby decreasing \nthe per-processor computational work. Benchmark data should be provided in either tabular or graphical form, or both; the speedup curve should \nbe supplied as well for strong scaling examples. Where appropriate, characterize the application's single-node performance (ex. percent of peak).", null=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Computational Approach'),
        ),
    ]
