# Generated by Django 4.2.11 on 2025-09-07 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_historicalproject_institution_project_institution"),
        ("project", "0011_auto_20240103_0856"),
    ]

    operations = []
