# Generated by Django 4.2.11 on 2025-09-07 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_merge_20250907_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="description",
            field=models.TextField(
                default="\nWe do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!\n        ",
                help_text="One-line description of the project.",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "The project description must be > 10 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "B",
                        "Large research project, connected to an european or international competitive project (up to 50.000 GPU hours per year, same size of an ISCRA AI allocation)",
                    ),
                    (
                        "BI",
                        "Large industrial research project (up to 50.000 GPU hours per year, same size of an ISCRA AI allocation)",
                    ),
                    (
                        "C",
                        "Medium research project, connected to a national competitive project or a small industrial research project (up to 10.000 GPU hours per year, same size of an ISCRA C allocation)",
                    ),
                    (
                        "T",
                        "Blue sky project, not connected to a competitive project (up to 5.000 GPU hours)",
                    ),
                    (
                        "D",
                        "PhD student support project (up to 5.000 GPU hours per year)",
                    ),
                    (
                        "F",
                        "Support to teaching, including group projects (up to 5.000 GPU hours)",
                    ),
                    ("E", "MSc thesis project (up to 2.000 GPU hours)"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                default="\nWe do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!\n        ",
                help_text="One-line description of the project.",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "The project description must be > 10 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "B",
                        "Large research project, connected to an european or international competitive project (up to 50.000 GPU hours per year, same size of an ISCRA AI allocation)",
                    ),
                    (
                        "BI",
                        "Large industrial research project (up to 50.000 GPU hours per year, same size of an ISCRA AI allocation)",
                    ),
                    (
                        "C",
                        "Medium research project, connected to a national competitive project or a small industrial research project (up to 10.000 GPU hours per year, same size of an ISCRA C allocation)",
                    ),
                    (
                        "T",
                        "Blue sky project, not connected to a competitive project (up to 5.000 GPU hours)",
                    ),
                    (
                        "D",
                        "PhD student support project (up to 5.000 GPU hours per year)",
                    ),
                    (
                        "F",
                        "Support to teaching, including group projects (up to 5.000 GPU hours)",
                    ),
                    ("E", "MSc thesis project (up to 2.000 GPU hours)"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
