# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.11 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_finalize_project_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="project_type_id",
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.projecttype",
            ),
        ),
    ]
