# Generated by Django 4.2.11 on 2026-03-25 10:30

import django.core.validators
from django.db import migrations
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0020_projectproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectproposal",
            name="computational_approach",
            field=martor.models.MartorField(
                blank=True,
                help_text="Provide quantitative evidence of the HPC performances of the production application you will adopt in the project (scalability, efficiency, \nI/O performances). Parallel performances in either strong or weak scaling mode should be provided. Weak scaling behaviors are probed by holding \nper-processor computational work constant (e.g., the size of the mesh on a processor is held constant) as the total problem size grows with number \nof processors. Strong scaling behaviors are probed by holding the total problem size constant as the processor count grows, thereby decreasing \nthe per-processor computational work. Benchmark data should be provided in either tabular or graphical form, or both; the speedup curve should \nbe supplied as well for strong scaling examples. Where appropriate, characterize the application's single-node performance (ex. percent of peak).",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20000)],
                verbose_name="Computational Approach",
            ),
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="description_of_research",
            field=martor.models.MartorField(
                blank=True,
                help_text="This section, including references, cannot exceed 20.000 char and is expected to detail how the specific scientific/computational goals will be achieved and to define detailed workplan.<br />\nProposals will be evaluated on both scientific and technical merit. The provided information should be sufficient for the reviewers in your research field to provide a scientific evaluation of the proposal and to understand if the computational methodology is suitable to reach the project's goals. Furthermore, a general scientific cross-comparison with proposals in other disciplines should be feasible.<br />\nThe list of the topics that MUST be detailed/included follows (please notice that incomplete descriptions will lead to the project rejection).<br />\n- Scientific framework<br />\n- Project objectives<br />\n- Theoretical and computational methods employed<br />\n- List of the applications to be used and their performance on parallel architectures (scalability and load-balancing)<br />\n- Detailed workplan and timetable of the activities (GANTT)<br />\n- Place the proposed research in the context of competing work in your discipline<br />\n- Explain what scientific advances you expect to be enabled by an award that justifies an allocation of large-scale resources",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20000)],
                verbose_name="Description of Research",
            ),
        ),
    ]
