# Generated by Django 4.2.11 on 2026-03-27 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0024_proposalreview_and_admin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectproposal",
            name="pi",
            field=models.ForeignKey(
                blank=True,
                help_text="The PI who will be responsible for the project. Defaults to the applicant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals_as_pi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Principal Investigator",
            ),
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="requested_gpu_hours",
            field=models.PositiveIntegerField(
                help_text="Number of GPU hours per year requested (1 standard budget hour = 1/6 GPU hour).",
                verbose_name="Requested GPU hours/year",
            ),
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="requested_storage_gb",
            field=models.PositiveIntegerField(
                help_text="Amount of WORK storage requested, in GB.",
                verbose_name="Requested storage (GB)",
            ),
        ),
    ]
