# Generated by Django 4.2.11 on 2026-03-27 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0025_projectproposal_add_pi"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectproposal",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional participants in the project (the PI will be added automatically).",
                related_name="proposal_team_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Research Team",
            ),
        ),
    ]
