# Generated by Django 4.2.11 on 2026-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0026_projectproposal_add_team_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectproposal",
            name="meta_review",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary review written by the committee, visible to the proposer, PI, and team. Must be written before the final decision can be taken.",
                verbose_name="Meta-review",
            ),
        ),
    ]
