# Generated by Django 4.2.11 on 2026-03-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0027_projectproposal_add_meta_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The proposal this project was created from, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.projectproposal",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proposal",
            field=models.OneToOneField(
                blank=True,
                help_text="The proposal this project was created from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provisioned_project",
                to="project.projectproposal",
            ),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="approved_gpu_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Admin-approved GPU hours/year (overrides the requested value on provisioning).",
                null=True,
                verbose_name="Approved GPU hours/year",
            ),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="approved_storage_gb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Admin-approved WORK storage in GB (overrides the requested value on provisioning).",
                null=True,
                verbose_name="Approved storage (GB)",
            ),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="project_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short identifier assigned by the admin (e.g. h2020_elliot). Will become the project title, SLURM account name, and WORK storage group.",
                max_length=64,
                verbose_name="Project code",
            ),
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="meta_review",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary review written by the committee. Visible to the proposer, PI, and team only after the final decision is taken. Must be written before a decision can be taken.",
                verbose_name="Meta-review",
            ),
        ),
    ]
