# Generated by Django 4.2.11 on 2026-03-28 08:36

import django.core.validators
from django.db import migrations
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0028_proposal_provisioning_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="computational_approach",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="description_of_research",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="financed_project_text",
        ),
        migrations.RemoveField(
            model_name="project",
            name="computational_approach",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description_of_research",
        ),
        migrations.RemoveField(
            model_name="project",
            name="financed_project_text",
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="computational_approach",
            field=martor.models.MartorField(
                blank=True,
                help_text="Provide quantitative evidence of the HPC performances of the production application you will adopt in the project (scalability, efficiency, I/O performances). Parallel performances in either strong or weak scaling mode should be provided. Weak scaling behaviors are probed by holding per-processor computational work constant (e.g., the size of the mesh on a processor is held constant) as the total problem size grows with number of processors. Strong scaling behaviors are probed by holding the total problem size constant as the processor count grows, thereby decreasing the per-processor computational work. Benchmark data should be provided in either tabular or graphical form, or both; the speedup curve should be supplied as well for strong scaling examples. Where appropriate, characterize the application's single-node performance (ex. percent of peak).",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20000)],
                verbose_name="Computational Approach",
            ),
        ),
    ]
