# Generated by Django 3.2.20 on 2024-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
