# Generated by Django 3.2.20 on 2024-07-28 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20240728_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DocumentationArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', martor.models.MartorField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.documentationarticle')),
            ],
            options={
                'verbose_name_plural': 'Documentation Articles',
            },
        ),
    ]
