# Generated by Django 3.2.20 on 2024-07-28 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20240728_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationarticle',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
