# Generated by Django 4.2.11 on 2024-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_news_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentationarticle",
            name="hash",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
    ]
