# Generated by Django 4.2.11 on 2024-08-13 12:46

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_documentationarticle_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationarticle",
            name="body",
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
