# Generated by Django 4.2.11 on 2025-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_alter_documentationarticle_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOnboardingRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("given_name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("unimore_id", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PhD Student", "PhD Student"),
                            ("Research grant", "Research grant"),
                            ("Research contract", "Research contract"),
                            ("Guest", "Guest"),
                            ("Structured personnel", "Structured personnel"),
                            ("Student doing a thesis", "Student doing a thesis"),
                            ("Student from a course", "Student from a course"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountonboardingrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Pending")),
                fields=("unimore_id", "status"),
                name="unique_pending_onboarding_request_per_user",
            ),
        ),
    ]
