# Generated by Django 4.2.11 on 2025-08-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_auto_20240103_0856"),
        ("portal", "0010_accountonboardingrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountonboardingrequest",
            name="course_project",
            field=models.ForeignKey(
                blank=True,
                help_text='Selected course (project) for users with role "Student from a course".',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_requests",
                to="project.project",
            ),
        ),
    ]
