# Generated by Django 4.2.11 on 2025-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_accountonboardingrequest_course_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountonboardingrequest",
            name="processed_in_ldap",
            field=models.BooleanField(
                default=False,
                help_text="Set to true once the LDAP provisioning job has created/updated the directory entry.",
            ),
        ),
    ]
