# Generated by Django 4.2.11 on 2025-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0012_accountonboardingrequest_processed_in_ldap"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accountonboardingrequest",
            name="unique_pending_onboarding_request_per_user",
        ),
        migrations.AddField(
            model_name="accountonboardingrequest",
            name="identity_document",
            field=models.FileField(
                blank=True,
                help_text="Required for users without a UNIMORE account (government-issued ID, student card, etc.).",
                null=True,
                upload_to="identity_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="accountonboardingrequest",
            name="unimore_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name="accountonboardingrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "Pending"),
                    models.Q(("unimore_id__isnull", True), _negated=True),
                    models.Q(("unimore_id", ""), _negated=True),
                ),
                fields=("unimore_id", "status"),
                name="unique_pending_onboarding_request_per_unimore_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountonboardingrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "Pending"),
                    models.Q(
                        ("unimore_id__isnull", True),
                        ("unimore_id", ""),
                        _connector="OR",
                    ),
                ),
                fields=("email", "status"),
                name="unique_pending_onboarding_request_per_external_email",
            ),
        ),
    ]
