# Generated by Django 4.2.11 on 2026-01-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_alter_historicalproject_description_and_more"),
        (
            "portal",
            "0013_remove_accountonboardingrequest_unique_pending_onboarding_request_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountonboardingrequest",
            name="course_project",
            field=models.ForeignKey(
                blank=True,
                help_text='Corso (progetto) selezionato per gli utenti con ruolo "Studente da un corso".',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_requests",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="accountonboardingrequest",
            name="role",
            field=models.CharField(
                choices=[
                    ("Studente di Dottorato", "Studente di Dottorato"),
                    ("Assegno di Ricerca", "Assegno di Ricerca"),
                    ("Contratto di Ricerca", "Contratto di Ricerca"),
                    ("Incarico di Ricerca", "Incarico di Ricerca"),
                    ("Incarico Post-Doc", "Incarico Post-Doc"),
                    ("Incarico di Collaborazione", "Incarico di Collaborazione"),
                    ("Ricercatore RTD-A", "Ricercatore RTD-A"),
                    ("Ricercatore RTD-B", "Ricercatore RTD-B"),
                    ("Ricercatore RTT", "Ricercatore RTT"),
                    ("Professore Associato", "Professore Associato"),
                    ("Professore Ordinario", "Professore Ordinario"),
                    ("Studente in tesi", "Studente in tesi"),
                    ("Studente da un corso", "Studente da un corso"),
                    ("Ospiti a vario titolo", "Ospiti a vario titolo"),
                ],
                max_length=40,
            ),
        ),
    ]
