# Generated by Django 4.2.11 on 2026-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0014_alter_accountonboardingrequest_course_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountonboardingrequest",
            name="codice_fiscale",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
