# Generated by Django 4.2.11 on 2026-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0015_accountonboardingrequest_codice_fiscale"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountonboardingrequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Optional reason shown to admins when the request is rejected.",
                null=True,
            ),
        ),
    ]
