# Generated by Django 4.2.11 on 2026-04-18 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0017_ldapuseredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRenewalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_username', models.CharField(db_index=True, max_length=150)),
                ('current_role', models.CharField(blank=True, max_length=40)),
                ('current_expiration_date', models.DateField(blank=True, null=True)),
                ('requested_expiration_date', models.DateField()),
                ('role_changed', models.BooleanField(default=False)),
                ('new_role', models.CharField(blank=True, choices=[('Studente di Dottorato', 'Studente di Dottorato'), ('Assegno di Ricerca', 'Assegno di Ricerca'), ('Contratto di Ricerca', 'Contratto di Ricerca'), ('Incarico di Ricerca', 'Incarico di Ricerca'), ('Incarico Post-Doc', 'Incarico Post-Doc'), ('Incarico di Collaborazione', 'Incarico di Collaborazione'), ('Ricercatore RTD-A', 'Ricercatore RTD-A'), ('Ricercatore RTD-B', 'Ricercatore RTD-B'), ('Ricercatore RTT', 'Ricercatore RTT'), ('Professore Associato', 'Professore Associato'), ('Professore Ordinario', 'Professore Ordinario'), ('Studente in tesi', 'Studente in tesi'), ('Studente da un corso', 'Studente da un corso'), ('Ospiti a vario titolo', 'Ospiti a vario titolo')], max_length=40)),
                ('proof_document', models.FileField(blank=True, help_text='Required when role has changed (e.g. new contract or appointment letter).', null=True, upload_to='renewal_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountrenewalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('requester_username', 'status'), name='unique_pending_renewal_per_user'),
        ),
    ]
