# Generated by Django 4.2.11 on 2026-04-19 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0029_remove_project_research_fields'),
        ('portal', '0018_accountrenewalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_username', models.CharField(db_index=True, max_length=150)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='project.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='courseenrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('requester_username', 'project', 'status'), name='unique_pending_enrollment_per_user_project'),
        ),
    ]
