# Generated by Django 4.2.11 on 2025-08-10 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("allocation", "0006_auto_20231224_0848"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalAllocationAttributeUsage",
        ),
    ]
