# Generated by Django 4.2.11 on 2026-03-28 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broadcastemail",
            name="failed_count",
        ),
        migrations.RemoveField(
            model_name="broadcastemail",
            name="sent_count",
        ),
    ]
