# Generated by Django 4.2.11 on 2024-08-13 09:53

import coldfront.core.grant.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grant", "0003_auto_20231224_0848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="direct_funding",
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name="grant",
            name="percent_credit",
            field=coldfront.core.grant.models.PercentField(
                max_length=100,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="total_amount_awarded",
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalgrant",
            name="direct_funding",
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalgrant",
            name="percent_credit",
            field=coldfront.core.grant.models.PercentField(
                max_length=100,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrant",
            name="total_amount_awarded",
            field=coldfront.core.grant.models.MoneyField(max_length=100),
        ),
    ]
