# Generated by Django 4.2.11 on 2024-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0003_auto_20231224_0848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="linked_resources",
            field=models.ManyToManyField(blank=True, to="resource.resource"),
        ),
    ]
